/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theforthtenant;

/**
 *
 * @author yuji
 */
public class LoadingScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoadingScreen.class.getName());
    
    // --- Loading fields ---
    private static final int LOAD_TIME_MS = 5000;
    private static final int TICK_MS = 50;
    private int elapsed = 0;
    private javax.swing.Timer progressTimer;

    private final String[] statusMessages = {
        "Loading core components...",
        "Reconstructing the timeline...",
        "Cross-referencing suspect alibis...",
        "Analyzing chemical residues...",
        "Piecing together torn documents...",
        "Decrypting encrypted files...",
        "Examining points of forced entry...",
        "Uncovering buried memories...",
        "Gathering evidences...",
        "Cleaning up crime scene..."
    };
    private int statusIndex = 0;
    
    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        setUndecorated(true);
        initComponents();
        
        // White + pixel font on all text
        jLabel1.setFont(getCustomFont(8f));      // "Initializing"
        jLabel1.setForeground(java.awt.Color.WHITE);

        jLabel2.setFont(getCustomFont(8f));       // status text (smaller, easier to read)
        jLabel2.setForeground(java.awt.Color.WHITE);
        
        setTitle("The Fourth Tenant");
        setResizable(false);
        setLocationRelativeTo(null);
        
        // Progress bar styling
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(0);
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setStringPainted(false);
        jProgressBar1.setBackground(new java.awt.Color(60, 60, 60));
        jProgressBar1.setForeground(new java.awt.Color(180, 180, 180));

        // Kick off the fake load
        startLoading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 20, 22));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Initializing");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, -1));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 280, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("status");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void startLoading() {
        progressTimer = new javax.swing.Timer(TICK_MS, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                elapsed += TICK_MS;
                int percent = (int) Math.min(100, (elapsed / (double) LOAD_TIME_MS) * 100);
                jProgressBar1.setValue(percent);

                // Cycle the status text proportionally to progress
                int newIndex = Math.min(statusMessages.length - 1,
                        (int) ((percent / 100.0) * statusMessages.length));
                if (newIndex != statusIndex) {
                    statusIndex = newIndex;
                    jLabel2.setText(statusMessages[statusIndex]);
                }

                if (percent >= 100) {
                    progressTimer.stop();
                    javax.swing.Timer delay = new javax.swing.Timer(400, new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            openMainMenu();
                        }
                    });
                    delay.setRepeats(false);
                    delay.start();
                }
            }
        });
        progressTimer.start();
    }

    private void openMainMenu() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            MainMenu menu = new MainMenu();
            menu.setLocationRelativeTo(null);
            menu.setVisible(true);
        });
        dispose();
    }
    
    private java.awt.Font getCustomFont(float size) {
        try {
            java.io.InputStream is = getClass().getResourceAsStream("/fonts/press_start_2p.ttf");
            java.awt.Font base = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, is);
            return base.deriveFont(size);
        } catch (Exception e) {
            System.out.println("Font not found! Using default.");
            return new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, (int) size);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoadingScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
